name: CI

on:
  push:
    branches: [ dev, main ]
  pull_request:
    branches: [ dev, main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Restore
        run: dotnet restore backend/SseDemo.sln
      - name: Build
        run: dotnet build --no-restore --configuration Release backend/SseDemo.sln
      - name: Test
        run: dotnet test --no-build --configuration Release --collect:"XPlat Code Coverage" backend/SseDemo.sln
